### ISSUE TITLE
[Feature Request]: Better document dsp/kfp version matrix, and include supported upstream sdk versions

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-tekton#115]
### Feature description

As a user of DSP I want to be able to easily figure out what vesion of DSP corresponds with what version of KFP. Furthermore, I want to be able to easily figure out what kfp-tekton sdk's are supported by each released DSP version.

Context: 
https://github.com/opendatahub-io/data-science-pipelines/issues/106#issuecomment-1658833139

Acceptance criteria: 
A markdown or similar doc format that is **_easy to find_** outlining the above.

**Comment by HumairAK** [comment]
Documented here: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/docs/release/compatibility.md

but I don't think this is "easy to find", so leaving this issue open for now

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1612
