### ISSUE TITLE
[Feature Request]: Upgrade to v1.7  kfp-tekton

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-tekton#118]
### Feature description

This issue tracks all issues required to upgrade to kfp-tekton 1.7 

Issues: 
* https://github.com/opendatahub-io/data-science-pipelines/issues/116
* https://github.com/opendatahub-io/data-science-pipelines-operator/issues/242
* https://github.com/opendatahub-io/data-science-pipelines-operator/issues/241
* https://github.com/opendatahub-io/data-science-pipelines-operator/issues/240

*Note* 
1.7 Requires tekton 0.47. This is introduced in OCP Pipeline 1.11. The earliest OCP adoption for this is 4.12. Which means We have to wait until OCP EOL's 4.11 before proceeding with this change.

Some additional commits that may need to be backported for 1.7 from upstream: 
* https://github.com/opendatahub-io/data-science-pipelines/pull/125 (only need substitution commit, not ee3cf4a)
* https://github.com/kubeflow/kfp-tekton/pull/1259

References:
[1] https://docs.openshift.com/container-platform/4.13/cicd/pipelines/op-release-notes.html
[2] https://github.com/kubeflow/kfp-tekton/tree/v1.6.6/sdk#project-prerequisites
[3] https://access.redhat.com/support/policy/updates/openshift#dates

**Comment by gmfrasca** [comment]
We need to do #120 first, and this will also depend on getting to a minimum supported openshift version that supports OpenShift Pipelines Operator with a sufficient Tekton engine (may not even be released yet).  This will likely be on hold for a while until then.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1614
