### ISSUE TITLE
[Feature Request]: Upgrade to v1.6.6 kfp-tekton

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-tekton#120]
### Feature description

Pull in changes from upstream kfp-tekton to bring us to version v1.6.6 (the lastest version that OCP 4.10 will support).  This is due to the Tekton Pipelines Operator dependency, and the latest provided version that is still available to our minimum supported OpenShift (4.10) is Tekton v0.44.

*Note* We need to ensure that the versions of OpenShift that require support for Tekton v0.33 (ocp 4.9) are officially EOL'd on all deployment streams before performing this action

Some additional commits that may need to be backported for 1.6 from upstream: 
* https://github.com/opendatahub-io/data-science-pipelines/pull/125 (only need substitution commit, not ee3cf4a)
* https://github.com/kubeflow/kfp-tekton/pull/1259

References:
[1] https://docs.openshift.com/container-platform/4.13/cicd/pipelines/op-release-notes.html
[2] https://github.com/kubeflow/kfp-tekton/tree/v1.6.6/sdk#project-prerequisites
[3] https://access.redhat.com/support/policy/updates/openshift#dates

**Comment by HumairAK** [comment]
@harshad16 fyi we'll be looking to tackle this for next sprint (starting oct 30), sync up with us on what elyra will need for this.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1615
