### ISSUE TITLE
[v2] Parametrize the launcher image

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-tekton#130]
As a follow up to https://github.com/opendatahub-io/data-science-pipelines/pull/127, we need to parameterize the launcher image so it's possible to extend/provide fixes to the code.

**Comment by DharmitD** [comment]
Created an issue in the upstream kfp-tekton repo: https://github.com/kubeflow/kfp-tekton/issues/1358

**Comment by rimolive** [comment]
Closing this issue as the PR was merged.
