### ISSUE TITLE
Set up OpenShift CI to build images for PRs

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/data-science-pipelines-tekton#14]
/kind feature

@LaVLaS recently set up image builds on PRs for odh-dashboard. We should set up the same for the ML Pipelines repository.

Related PRs:
1) https://github.com/openshift/release/pull/30719
2) https://github.com/openshift/release/pull/31401

**Comment by DharmitD** [comment]
PR to set up OpenShift CI for ODH ML pipelines repository along with back end unit tests: https://github.com/openshift/release/pull/31575

**Comment by HumairAK** [comment]
closing in favor of: https://github.com/opendatahub-io/data-science-pipelines/issues/92
