### ISSUE TITLE
[Feature Request]: Prevent deletion of running Runs

### ISSUE THREAD

**Issue by roytman** [opendatahub-io/data-science-pipelines-tekton#146]
### Feature description

Our KFP runs create Ray clusters, so we use `ExitHandler` to remove the clusters. With setting `erminateStatus: CancelledRunFinally` in the relevant `DataSciencePipelinesApplication`, we can guarantee that the `ExitHandler` will be executed if a Run is stopped. 
However, when a running Run is deleted, the `ExitHandler` is not executed, and it leaves a lot of orphan resources. 

If users, before deleting a Run, should stop it we would not have this issue. 

### Describe alternatives you've considered

Guarantee to execute `ExitHandler` when a Run is deleted.

**Comment by andrewballantyne** [comment]
@HumairAK We can stop it before invoking a delete -- but I do not believe this is a UI fix. Backend needs to stop runs if that's a desired operation to precede a delete operation be it upstream or DS Pipelines. We are 1 of many touch points with the API. We can definitely look to support this on our side in the short term, but it's a stop-gap, this problem will not be "fixed" if it is just us.

FWIW. We have a need to support/show ExitHandlers here:
- https://github.com/opendatahub-io/odh-dashboard/issues/1751

**Comment by gmfrasca** [comment]
Leaving ticket as is, but depending on complexity may split this issue into smaller parts

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1616
