### ISSUE TITLE
Performance enhancement: Update pipelineloop to use informer instead of lister for updating pipeline status.

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-tekton#150]
Original issue: https://github.com/kubeflow/kfp-tekton/issues/1357

**Note**:
This is a reference issue for internal tracking purposes, please forward all discussion to the actual upstream issue.
When assigning this, please confirm this is already not in progress upstream.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1617
