### ISSUE TITLE
 feature(backend) Status-IR: add MLMD client to persistence agent and support for Status-IR

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-tekton#151]
Original Issue: https://github.com/kubeflow/pipelines/issues/8964

This issue looks like it's gone stale, reach out to kfp community and see if we can help contribute to this effort.

**Note**:
This is a reference issue for internal tracking purposes, please forward all discussion to the actual upstream issue.
When assigning this, please confirm this is already not in progress upstream.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1618
