### ISSUE TITLE
[Bug]: GH Actions/CI on the PR failing

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/data-science-pipelines-tekton#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Standalone DSPO (without ODH)

### Version

kfpv2

### Environment

GH Actions/workflows.

### Current Behavior

The GH action checks on PRs to this repository are failing. 

```
This is the test case failing among unit tests:
--- FAIL: TestNestedLoop (0.78s)
    --- FAIL: TestNestedLoop/{yamlPath:testdata/nestedloop_ir.yaml_platformSpecPath:_tektonYAMLPath:testdata/nestedloop.yaml} (0.78s)
FAIL
	github.com/kubeflow/pipelines/backend/src/v2/compiler/tektoncompiler	coverage: 76.7% of statements
FAIL	github.com/kubeflow/pipelines/backend/src/v2/compiler/tektoncompiler	2.606s
?   	github.com/kubeflow/pipelines/backend/src/v2/config	[no test files]
?   	github.com/kubeflow/pipelines/backend/src/v2/controller	[no test files]
```

And for the integration tests, the pipeline gets created but run creation fails:
```
  Status of flip-coin run: RUNNING
  Status of flip-coin run: FAILED
 =====   flip-coin FAILED =====
/home/runner/work/data-science-pipelines/data-science-pipelines/sdk/python/kfp/client/client.py:158: FutureWarning: This client only works with Kubeflow Pipeline v2.0.0-beta.2 and later versions.
  warnings.warn(
Are you sure you want to delete run 0d2172e5-c15a-494c-bb8e-5a8ab8e04ba5? [y/N]: Run 0d2172e5-c15a-494c-bb8e-5a8ab8e04ba5 deleted.
e2e test FAILED
```

Find an example test PR with the CI checks failed here: https://github.com/opendatahub-io/data-science-pipelines/pull/152

### Expected Behavior

All the CI checks should pass.

**Comment by DharmitD** [comment]
Leaving t[he test PR](https://github.com/opendatahub-io/data-science-pipelines/pull/152) open to be utilized for further investigation through the CI logs. Please close the PR once done with this issue.

**Comment by gregsheremeta** [comment]
duplicate of #155 , closing
