### ISSUE TITLE
Fix tests for kfpv2 branch

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-tekton#155]
Currently all gh tests are failling when new PRs are coming. They are:

* run-go-unittests
* backend-integration

We need to find out what it makes them to fail, and fix. NOTE: It might be important check if these tests are running fine in kfp-tekton repo and rebase dsp repo if needed.

**Comment by gregsheremeta** [comment]
we suspect not needed after all :)  @rimolive to check into it and probably close

@rimolive can use @DharmitD 's test PR (link here)

**Comment by DharmitD** [comment]
Find a test PR here to investigate further: https://github.com/opendatahub-io/data-science-pipelines/pull/152

**Comment by HumairAK** [comment]
Let's verify that v2 ci for the dspv2 is working

**Comment by rimolive** [comment]
Closing as v2 ci is working fine
