### ISSUE TITLE
Write an ADR for Argo vs. Tekton as the backend pipeline engine in DSP

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-tekton#156]

**Comment by rimolive** [comment]
ADR PR Link: https://github.com/opendatahub-io/architecture-decision-records/pull/22

**Comment by gregsheremeta** [comment]
moved to:
[internal doc] https://docs.google.com/document/d/1Wu9QPAnI3h6HKahvBr6vX-63IFR7oRDHhawSmw0azWQ/edit
