### ISSUE TITLE
[Bug]: Asterisk in the pipeline node Output files gets encoded to %2A 

### ISSUE THREAD

**Issue by rossbrigoli** [opendatahub-io/data-science-pipelines-tekton#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

ODH Dashboard UI

### Version

Red Hat OpenShift Data Science 1.33.0

### Environment

OpenShift Version: 4.13.9
Pipelines Version: 1.12.1

### Current Behavior

While designing a pipeline in the workbench, I added an output file in one of the node.

The output file I  added is a directory path formatted as "openvino/*". This directory contains model binaries.

The pipeline fails because the * is encoded as %2A when executed in the Data Science pipeline.

According to Elyra pipelines docu, wildcards in the output path is supported. https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html#output-files

### Expected Behavior

The pipeline should accept wildcards in the node's output file path.

### Steps To Reproduce

1. Create an elyra pipeline in the workbench.
2. Add one python file node, the python file should generate a file under a subdirectory "model"
3. Configure the node to have an Output file
4. Set the value of the output file to "model/*"
5. Export the pipeline as KFP yaml file
6. Import the KFP yaml file onto the pipeline server
7. Run the pipeline

### Workaround (if any)

I had to manually declare output files for each file in the sub directory. It works if you only have few files.

**Comment by HumairAK** [comment]
@harshad16 can you confirm if this is a workbench issue? it sounds like elyra is supposed to do wildcard expansion here

**Comment by harshad16** [comment]
yes this a workbench side of issue.
Lets transfer it to us.

/transfer notebooks

**Comment by HumairAK** [comment]
@harshad16 I don't think this transferred

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1620
