### ISSUE TITLE
component-mlmd overlay is not working.

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-tekton#60]
/kind bug

When adding component-mlmd overlay, metadata-writer pod fails to deploy 

**What did you expect to happen:**
MLMD components deployed

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by HumairAK** [comment]
stale issue, we now have a working mlmd prototype and are in process of adding this as an optional component to dspo: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/129
