### ISSUE TITLE
[Feature Request] Add tags to DSP repo to provide snapshots for stable releases during development

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/data-science-pipelines-tekton#66]
/kind feature

**Description:**
We should be tagging the default branch when features or fixes are added to allow references for users who want pull stable releases of the code and manifest.  These tags would provide a reference point for anyone that wants to track changes in the codebase between upgrades.

This would also provide a compatibility matrix to between versions KF upstream -> DSP -> ODH Release

**Additional information:**
These tags would also be used as references when including a component release in an ODH release.  If DSP tags a stable release `vX.Y.Z` then that release manifest could be included in ODH `vA.B.Z`.

**Comment by HumairAK** [comment]
We have tagged releases now, so I believe this should be completed: https://github.com/opendatahub-io/data-science-pipelines/releases 
They are also referenced within odh releases by their tag versions. Marking complete.
