### ISSUE TITLE
[Feature request] Define architectural methods and steps to configure access credentials and secrets

### ISSUE THREAD

**Issue by yuanchi2807** [opendatahub-io/data-science-pipelines-tekton#72]
**Description:**
In addition to function definition and base image for a data science pipeline component, many applications require access to data stored in priviledged accounts. Need to define a set of architectural methods and steps to configure the execution environment with credentials and secrets, such as image pull and s3fs mount. 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1603
