### ISSUE TITLE
[Feature request] Capture pipeline metadata to track run lineage

### ISSUE THREAD

**Issue by yuanchi2807** [opendatahub-io/data-science-pipelines-tekton#73]
**Description:**
Capture aritifacts and their metadata in data science pipelines so their owners could establish lineage including input/output data locations, versions of data and model and resulting metrics, if applicable. Such lineage should allow reproducible execution of the pipeline. 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by HumairAK** [comment]
This will be addressed via: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/335

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1604
