### ISSUE TITLE
[Feature request] Improve iris-sklearn sample

### ISSUE THREAD

**Issue by jgarciao** [opendatahub-io/data-science-pipelines-tekton#84]
/kind feature

**Description:**

In [this Jira issue](https://issues.redhat.com/browse/RHODS-7774) we identified a couple of improvements in the iris-sklearn sample and @strangiato proposed possible solutions:
- In the STEP-MAIN task, add a function in to convert the index to the named label to make the result more intuitive
- Fix the warning below with the solution proposed in [the Jira issue](https://issues.redhat.com/browse/RHODS-7774)
`/opt/app-root/lib64/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names`

**Comment by gregsheremeta** [comment]
might be superseded by [#174](https://github.com/opendatahub-io/data-science-pipelines-operator/issues/174)

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1607
