### ISSUE TITLE
Limit MLMD v1 to Specific DSPA

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-tekton#95]
/kind feature

**Description:**
MLMD currently watches all Tekton pods in a given *Namespace* which breaks any idea of having multiple Data Science Pipelines Application stacks in the same OpenShift/DataScience Project.  Implement some sort of label/annotation filtering such that a specific MLMD component only reads for a single DSPA target.

**Comment by rimolive** [comment]
This is a v1 issue, not a v2 one. This is because in v1 there is a pod that writes metadata about all pipelines, while in v2 this is done programatically.

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1608
